- name: variable preference
  hosts: localhost
  vars:
    WISHES: "Morning from PLAY variable"
  vars_files:
  - vars.yml
  # vars_prompt:
  #   - name: WISHES
  #     prompt: enter the WISHES
  #     private: false
  tasks:
    - name : variable info
      #vars:
       # WISHES: "Morning from TASK variable"
      ansible.builtin.debug:
        msg: "Hello , Good {{WISHES}}"


        # arguments
        # TASK
        # variable file
        # prompt