- name: conditions
  hosts: web
  tasks:
    - name: conditions info
      ansible.builtin.command: id expense
      ignore_errors: yes
      register: USERNAME

    - name: print user info
      ansible.builtin.debug:
        msg: "userinfo is : {{USERNAME}}"

    - name: create user
      ansible.builtin.command: useradd expense
      when: USERNAME.rc != 0 #condition 

    - name: say Hello
      ansible.builtin.debug:
        msg: "HELLO"
        