- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: installing the packages
    ansible.builtin.dnf:
      name: " {{item}} "
      state: latest
    loop:
    - nginx
    - postfix