172.31.64.85

[web]
172.31.69.109

[db]
172.31.64.87

[app]
172.31.64.88

[localhost]
localhost

[localhost:vars]

COURSE="Devops"
TRAINER="siva kumar"
DURATION="120 hrs"
#WISHES="Morning from inventory"

[all:children]
web
db
app
